image: cedricfarinazzo/archlinux-criterion-c:latest

stages:
  - build
  - coverage
  - test
  - install
  - doc
  - webhook

#before_script:
#  - pacman -Syyu --noconfirm


##################
# BUILD STAGE
job_build_gcc:
  stage: build
  artifacts:
    untracked: true
  variables:
      CC: gcc
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make CC=${CC}

job_build_clang:
  stage: build
  artifacts:
    untracked: true
  variables:
      CC: clang
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make CC=${CC}

job_build_scan-build:
  stage: build
  artifacts:
    paths:
      - report/*
  variables:
      CC: clang
  script:
    - mkdir build
    - cd build
    - scan-build cmake -DCMAKE_C_COMPILER=clang ..
    - scan-build -analyze-headers -stats -maxloop 8 -o ../report make -j4


################
# COVERAGE STAGE
# GCOV
job_coverage_gcov:
  stage: coverage
  dependencies:
    - job_build_gcc
  artifacts:
    untracked: true
  script:
    - cd build
    - make coverage


################
# TEST STAGE
# GCC
job_test_main_gcc:
  stage: test
  dependencies:
    - job_build_gcc
  script:
    - cd build
    - make run

job_test_criterion_gcc:
  stage: test
  dependencies:
    - job_build_gcc
  script:
    - cd build
    - make check

# CLANG
job_test_main_clang:
  stage: test
  dependencies:
    - job_build_clang
  script:
    - cd build
    - make run

job_test_criterion_clang:
  stage: test
  dependencies:
    - job_build_clang
  script:
    - cd build
    - make check


#############
# INSTALL STAGE
job_install_gcc:
  stage: install
  variables:
      CC: gcc
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=RELWITHDEBINFO ..
    - make CC=${CC}
    - sudo make install

#############
# DOC STAGE
job_doc:
  stage: doc
  artifacts:
    paths:
      - build/doc/
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make doc

#############
# WEBHOOK STAGE
job_success:
    stage: webhook
    script:
        - wget https://gitlab.com/cedricfarinazzo/gitlab-ci-discord-webhook/raw/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL
    when: on_success
    allow_failure: true


job_failure:
    stage: webhook
    script:
        - wget https://gitlab.com/cedricfarinazzo/gitlab-ci-discord-webhook/raw/master/send.sh
        - chmod +x send.sh
        - ./send.sh failure $WEBHOOK_URL
    when: on_failure
    allow_failure: true
